sudo: true
language: python
python:
  - 3.6.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
install:
  - pip install -r .travis_requirements.txt
  - pip install pygame
script:
  - python tests/unit_tests/imgs_load.py
