CORRECT_ORDER = "You have completed an order - translated the key and returned the object!"
INCORRECT_ORDER = "Order incorrect. Ticket and food do not match."
NO_HASH = "You must use the hasher to find the value.  Ticket deleted, pick up new ticket."
PICK_UP_FOOD_AND_TICKET = "Pick up a ticket from the ticket window and food from the countertop"
PICK_UP_FOOD = "Pick up food from the countertop first.  Ticket deleted, pick up new ticket."
PICK_UP_TICKET = "Pick up a ticket from the ticket window before you pick up the food from the counterop"